# [𝝺] Low-level functional API

## Functional evolution

First let's set up a module to play with:

In [1]:
# - Rockpool imports
from rockpool.nn.modules import RateJax

# - Switch off warnings
import warnings
warnings.filterwarnings('ignore')

# - Other useful imports
import numpy as np

try:
    from rich import print
except:
    pass

# - Construct a module
N = 3
mod = RateJax(N)

/Users/dylanaictx/SynSense Dropbox/Dylan Muir/LiveSync/Development/rockpool_GIT/rockpool/nn/modules/__init__.py:45: UserWarning: Sinabs modules not available: 'Slayer' backend not found. Modules that rely on Sinabs-Slayer will not be available.
  warnings.warn(f"Sinabs modules not available: {err}")
WARNING    /Users/dylanaictx/SynSense Dropbox/Dylan Muir/LiveSync/Development/rockpool_GIT/rockpool/nn/modules/__init__.py:63: UserWarning: NEST modules not available: 'NEST' backend not found. Modules that rely on NEST will not be available.
  warnings.warn(f"NEST modules not available: {err}")
 [py.warnings]


Could not import package: No module named 'iaf_nest'


Now if we evolve the module, we get the outputs we expect:

In [2]:
# - Set up some input
T = 10
input = np.random.rand(T, N)
output, new_state, record = mod(input)

In [3]:
print('output:', output)

output: [[[0.06522948 0.08927355 0.00719434]
  [0.13052788 0.12510219 0.00774908]
  [0.13059278 0.13205282 0.01822269]
  [0.16440758 0.20989072 0.07342938]
  [0.24516177 0.24915984 0.15610647]
  [0.3188888  0.23084876 0.23498613]
  [0.32221848 0.2171672  0.2625375 ]
  [0.29676253 0.28210646 0.30940053]
  [0.34721866 0.28456247 0.33214957]
  [0.396594   0.29321536 0.37236482]]]

In [4]:
print('new_state:', new_state)

new_state:
{
    'x': DeviceArray([0.396594  , 0.29321536, 0.37236482], dtype=float32),
    'rng_key': array([ 394923678, 1761837638], dtype=uint32)
}

In [6]:
print('mod.state:', mod.state())
print(mod.state()['x'], ' != ', new_state['x'])

mod.state:
{
    'rng_key': array([3735967969, 3067367654], dtype=uint32),
    'x': DeviceArray([0., 0., 0.], dtype=float32)
}

[0. 0. 0.]  !=  [0.396594   0.29321536 0.37236482]

In [7]:
mod = mod.set_attributes(new_state)
print(mod.state()['x'], ' == ', new_state['x'])

[0.396594   0.29321536 0.37236482]  ==  [0.396594   0.29321536 0.37236482]

## Functional state and attribute setting

In [8]:
new_tau = mod.tau * .4
mod.tau = new_tau
print(new_tau, ' == ', mod.tau)

[0.004 0.004 0.004]  ==  [0.004 0.004 0.004]

In [9]:
params = mod.parameters()
params['tau'] = params['tau'] * 3.

# - Note the functional calling style
mod = mod.set_attributes(params)

# - check that the attribute was set
print(params['tau'], ' == ', mod.tau)

[0.012 0.012 0.012]  ==  [0.012 0.012 0.012]

## Functional module reset

In [10]:
# - Reset the module state
mod = mod.reset_state()

# - Reset the module parameters
mod = mod.reset_parameters()

## Jax flattening