# [𝝺] Low-level functional API

## Functional evolution

First let's set up a module to play with:

In [1]:
# - Switch off warnings
import warnings
warnings.filterwarnings('ignore')

# - Rockpool imports
from rockpool.nn.modules import RateJax

# - Other useful imports
import numpy as np

try:
    from rich import print
except:
    pass

# - Construct a module
N = 3
mod = RateJax(N)

Could not import package: No module named 'iaf_nest'


Now if we evolve the module, we get the outputs we expect:

In [2]:
# - Set up some input
T = 10
input = np.random.rand(T, N)
output, new_state, record = mod(input)

In [3]:
print('output:', output)

output: [[[0.02114696 0.00989053 0.03182354]
  [0.04654327 0.03433599 0.06666339]
  [0.08230176 0.05535971 0.07213248]
  [0.12332115 0.05678442 0.08073001]
  [0.13181739 0.09974151 0.07767531]
  [0.13560757 0.09651617 0.09148949]
  [0.1767954  0.10431428 0.11117382]
  [0.21250004 0.1332448  0.12745431]
  [0.23403281 0.15806702 0.12969883]
  [0.23632057 0.19107696 0.1703079 ]]]

In [4]:
print('new_state:', new_state)

new_state:
{
    'x': DeviceArray([0.23632057, 0.19107696, 0.1703079 ], dtype=float32),
    'rng_key': array([ 808257824, 3588456238], dtype=uint32)
}

In [5]:
print('mod.state:', mod.state())
print(mod.state()['x'], ' != ', new_state['x'])

mod.state:
{
    'rng_key': array([1432838885, 1403173352], dtype=uint32),
    'x': DeviceArray([0., 0., 0.], dtype=float32)
}

[0. 0. 0.]  !=  [0.23632057 0.19107696 0.1703079 ]

In [6]:
mod = mod.set_attributes(new_state)
print(mod.state()['x'], ' == ', new_state['x'])

[0.23632057 0.19107696 0.1703079 ]  ==  [0.23632057 0.19107696 0.1703079 ]

## Functional state and attribute setting

In [7]:
new_tau = mod.tau * .4
mod.tau = new_tau
print(new_tau, ' == ', mod.tau)

[0.008 0.008 0.008]  ==  [0.008 0.008 0.008]

In [8]:
params = mod.parameters()
params['tau'] = params['tau'] * 3.

# - Note the functional calling style
mod = mod.set_attributes(params)

# - check that the attribute was set
print(params['tau'], ' == ', mod.tau)

[0.024 0.024 0.024]  ==  [0.024 0.024 0.024]

## Functional module reset

In [9]:
# - Reset the module state
mod = mod.reset_state()

# - Reset the module parameters
mod = mod.reset_parameters()

## Jax flattening